{% set name = "Cm" %}
{% set version = "9.0.1" %}
{% set tag = "v9r0p1" %}

package:
   name: "{{ name|lower }}"
   version: "{{ version }}"

source:
   url: https://git.ligo.org/virgo/virgoapp/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
   sha256: 65b04a591957d892cc33bda46f679ea23fa865ee98f280fb8b3de7da74621a72

build:
  number: 0
  skip: True  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - meson >=0.49
    - ninja
    - bison
    - flex
    - pkg-config

test:
  requires:
    - pkg-config
  commands:
    - test -x ${PREFIX}/bin/cm  # [unix]
    - test -x ${PREFIX}/bin/NameServer  # [unix]
    - test -f ${PREFIX}/lib/libcm.so  # [unix]
    - pkg-config --print-errors --modversion cm

about:
  home: https://git.ligo.org/virgo/virgoapp/Cm/
  dev_url: https://git.ligo.org/virgo/virgoApp/Cm/
  license: BSD-4-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A multitask communication package
  description: |
    The Cm package is an attempt to make simple and system 
    independant the task-to-task communication problem. It 
    covers the communication between tasks that operate on 
    different operating systems, different architectures by 
    hiding every detail of the use of TCPIP on which it is based.

extra:
  recipe-maintainers:
      - rhyspoulton
      - fcarbogn 
