{% set name = "Cm" %}

{% set version = "10.3.3" %}

package:
   name: "{{ name|lower }}"
   version: "{{ version }}"

source:
   url: http://software.igwn.org/sources/source/{{ name|lower }}-{{ version }}.tar.gz
   sha256: 54842f4d44d71792fb6860bb09ede138a04c4c038f8b24c1cc59834e873ef562

build:
  run_exports:
    - {{ pin_subpackage("cm", max_pin="x") }}
  number: 0
  skip: True  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - meson >=0.49
    - ninja
    - bison
    - flex
    - pkg-config

test:
  requires:
    - pkg-config
  commands:
    - test -x ${PREFIX}/bin/cm  # [unix]
    - test -x ${PREFIX}/bin/CmNameServer  # [unix]
    - test -x ${PREFIX}/bin/NameServer.start  # [unix]
    - test -f ${PREFIX}/lib/libcm.so  # [unix]
    - pkg-config --print-errors --modversion cm

about:
  home: https://git.ligo.org/virgo/virgoapp/Cm/
  dev_url: https://git.ligo.org/virgo/virgoApp/Cm/
  license: BSD-4-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A multitask communication package
  description: |
    The Cm package is an attempt to make simple and system 
    independant the task-to-task communication problem. It 
    covers the communication between tasks that operate on 
    different operating systems, different architectures by 
    hiding every detail of the use of TCPIP on which it is based.

extra:
  recipe-maintainers:
      - rhyspoulton
      - fcarbogn 
